appenders = console

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%-5level] %d{yyyy-MM-dd HH:mm:ss} [%t] %c{1} - %msg%n

loggers = app, hibernate

logger.app.name = com.flavfinder
logger.app.level = debug
logger.app.appenderRefs = console
logger.app.appenderRef.console.ref = STDOUT
logger.app.additivity = false

logger.hibernate.name = org.hibernate
logger.hibernate.level = warn
logger.hibernate.appenderRefs = console
logger.hibernate.appenderRef.console.ref = STDOUT
logger.hibernate.additivity = false

rootLogger.level = error
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = STDOUT
